name: Backend Testing CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn -B clean test --file back/pom.xml

      - name: Run Integration Tests
        run: mvn -B verify -P integration-tests --file back/pom.xml

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            back/target/surefire-reports/
            back/target/failsafe-reports/
          retention-days: 30

      - name: Security vulnerability check
        run: mvn org.owasp:dependency-check-maven:check --file back/pom.xml
        continue-on-error: true